import registerProductIPC from "./ipc/product.ipc";
import registerPaymentsIPC from "./ipc/payments.ipc";
import registerCurrenciesIPC from "./ipc/currencies.ipc";
import registerCustomersIPC from "./ipc/customers.ipc";
import registerFundIPC from "./ipc/funds.ipc";
import registerProductBarcodeIPC from "./ipc/product_barcode.ipc";
import registerPurchaseInvoicesIPC from "./ipc/purchase_invoice.ipc";
import registerSalesInvoiceIPC from "./ipc/sales_invoice.ipc";
import registerSuppliersIPC from "./ipc/suppliers.ipc";
import registerTaxesIPC from "./ipc/taxes.ipc";
import registerUnitIPC from "./ipc/unit.ipc";
import registerCompanySettingIPC from "./ipc/company_setting.ipc";
import registerSerialIPC from "./ipc/serial.ipc";
import registerPartnersIPC from "./ipc/partners.ipc";
import registerExpenseIPC from "./ipc/expense.ipc";
import registerExpenceCategoryIPC from "./ipc/expence_category.ipc";
import registerPartyHistoryIPC from "./ipc/party_history.ipc";
import registerCustomerDisplayIPC from "./ipc/customer_display.ipc";
import registerAuthHandlersIPC from "./ipc/Auth.ipc";
import registerPurchaseReturnIPC from "./ipc/purchase_returns.ipc";
import registerSalesReturnsIpc from "./ipc/sales_returns.ipc";
import registerPrintDocsIPC from "./ipc/printDocs.ipc";
import registerSalesQuotationsIPC from "./ipc/sales_quotations.ipc";
import registerReportsIPC from "./ipc/reportsIpc";

export default function registerAllIPC() {
  registerAuthHandlersIPC();
  registerCustomerDisplayIPC();
  registerCompanySettingIPC();
  registerCurrenciesIPC();
  registerCustomersIPC();
  registerFundIPC();
  registerPaymentsIPC();
  registerProductBarcodeIPC();
  registerProductIPC();
  registerPurchaseInvoicesIPC();
  registerSerialIPC();
  registerSalesInvoiceIPC();
  registerSalesQuotationsIPC();
  registerSuppliersIPC();
  registerTaxesIPC();
  registerUnitIPC();
  registerPartnersIPC();
  registerExpenseIPC();
  registerExpenceCategoryIPC();
  registerPartyHistoryIPC();
  registerPurchaseReturnIPC();
  registerSalesReturnsIpc();
  registerPrintDocsIPC();
  registerReportsIPC();
}
